config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render


urlpatterns = [
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^', include('generator.urls', namespace='generator'))
]


def handler404(request, exception=None):
    return render(request, '400.html', {'exception': exception}, status=404)


def handler500(request, exception=None):
    return render(request, '500.html', {'exception': exception}, status=500)

generator/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^success/(?P<short_url>[A-Za-z0-9]{6})/$', views.SuccessView.as_view(), name='get-success'),
    url(r'^(?P<short_url>[A-Za-z0-9]{6})/$', views.GetOriginalView.as_view(), name='get-original'),
    url(r'^$', views.ShortenUrlView.as_view(), name='shorten-home'),
]

generator/models.py
from django.db import models
from django.utils.translation import ugettext as _

from .managers import UrlManager


class UrlModel(models.Model):
    original_url = models.URLField(blank=True, verbose_name=_('original url'))
    short_url = models.SlugField(max_length=10, unique=True, verbose_name=_('short url'))
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('created date'))

    objects = UrlManager()

    def __str__(self):
        return self.original_url

    def get_absolute_url(self):
        return '/{0}'.format(self.original_url)

generator/forms.py
from django import forms
from django.conf import settings

from .models import UrlModel
from .utils import generate_a_short_url


class UrlForm(forms.ModelForm):

    class Meta:
        model = UrlModel
        fields = ['original_url']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.short_url = generate_a_short_url(size=settings.SHORT_URL_LENGTH)
        if commit:
            instance.save()
        return instance

generator/views.py
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views import View
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.urls import reverse

from .models import UrlModel
from .forms import UrlForm
from .utils import generate_a_short_url


class SuccessView(TemplateView):

    template_name = "generator/redirect_by_short_url.html"

    def get_context_data(self, **kwargs):
        context = super(SuccessView, self).get_context_data(**kwargs)
        context['url_obj'] = get_object_or_404(
            UrlModel,
            short_url=self.kwargs.get('short_url')
        )
        return context


class ShortenUrlView(CreateView):
    model = UrlModel
    form_class = UrlForm
    template_name = 'home.html'

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse('generator:get-success', args=[self.object.short_url]))


class GetOriginalView(View):

    def get(self, request, short_url):
        url = get_object_or_404(UrlModel, short_url=short_url)
        return HttpResponseRedirect(url.original_url)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Generator</title>
    <link href="https://fonts.googleapis.com/css?family=Pangolin" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/generator/redirect_by_short_url.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="body-text center-text">
        <p>{% trans "The short link " %}<b><a href="{{ request.scheme }}://{{ request.get_host }}/{{ url_obj.short_url }}">{{ url_obj.short_url }}</a></b> {% trans "was generated from " %}<b><a href="{{ url_obj.original_url }}">{{ url_obj.original_url }}</a></b>!</p>
        <p class='center'>
            <a href="{% url 'generator:shorten-home' %}">{% trans "back to the home page" %}</a>
        </p>
    </div>
{% endblock content %}

templates/generator/url_was_generated.html
{% extends 'base.html' %}

{% block content %}
<div class="body-text center-text">
    <p>The <b>{{generated_url.short_url}}</b> url was generated from <b>{{ generated_url.original_url }}</b>!</p>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div>
    <div class="center-text">
        <p>{% trans "Hello! This is a simple Django App generating custom urls from your browser Addres Bar" %}!</p>
    </div>
    <div class="body-text">
        <div class="instruction">
            <p class="center">{% trans "Generate a short url here" %}:</p>
            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Shorten your url"/>
            </form>
            <p>{% trans "After generating your short link, you can simply get it entering `localhost:8000/your_short_link/` in the browser." %}</p>
            <p>{% trans "To manage urls click do the following" %}:</p>
            <p>click <a href="{% url 'admin:index' %}">here</a> and paste credentials(both fields - 'admin').</p>
        </div>
    </div>
</div>
{% endblock content %}